# Generated by Django 3.2.10 on 2022-07-15 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Sub Title')),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1024, verbose_name='Book Summary')),
                ('isbn', models.CharField(blank=True, help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=13, null=True, verbose_name='ISBN')),
                ('publish_year', models.CharField(blank=True, max_length=256, null=True, verbose_name='Book Publish Year')),
                ('book_status', models.CharField(choices=[('book_borrow', 'Book BORROWED'), ('book_available', 'Book AVAILABLE')], default='book_available', max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='BookPublisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='BookBorrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_application_date', models.DateField(blank=True, help_text='Used to store new book application date', null=True, verbose_name='Book Application Date')),
                ('book_issue_date', models.DateField(blank=True, help_text='Used to store book issue date', null=True, verbose_name='Book Issue Date')),
                ('book_return_date', models.DateField(blank=True, help_text='Used to store book return date', null=True, verbose_name='Book Return Date')),
                ('is_book_issued', models.BooleanField(default=False, verbose_name='Is book issued?')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_management.book')),
                ('book_issuer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_issuer', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_management.bookauthor'),
        ),
        migrations.AddField(
            model_name='book',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='book_management.bookpublisher'),
        ),
    ]
